"""
Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with 1 and 2, the first 10 terms will be:
1, 2, 3, 5, 8, 13, 21, 34, 55, 89
By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the even-valued terms.
"""

sequence = []
a, b = 1, 2

while a < 4000000:
    sequence.append(a)
    a, b = b, a + b

print(sequence)
print(sum(sequence))

numbers = []
count = 0
for i in range(len(sequence)):
    if sequence[i] % 2 == 0:
        numbers.append(sequence[i])

print(sum(numbers))

"""
Answer: 4613732
"""